### ISSUE TITLE
update_crontab_entry.py not in RUNNABLE after running build.py

### ISSUE THREAD

**Issue by yyzhuang** [SeattleTestbed/nodemanager#103]
When running unit test `python utf.py -m nm`, nodemanager log produced this error:

"The following error occured when modifying the crontab for the new 2009 seattle crontab entry: Traceback (most recent call last):
  File "nmmain.py", line 556, in main
ImportError: No module named update_crontab_entry"

The file update_crontab_entry.py is located under /dist: https://github.com/SeattleTestbed/dist

After adding update_crontab_entry.py in RUNNABLE, this error disappears.

**Comment by JustinCappos** [comment]
Right.  The logical fix may be to move it from dist to the node manager
repo.

@aaaaalbert: do you foresee any problems with this?

**Comment by yyzhuang** [comment]
Pull request: https://github.com/SeattleTestbed/nodemanager/pull/106

**Comment by aaaaalbert** [comment]
Sounds reasonable to me, although I would not expect too many pre-2009 Seattle crontab entries in the wild these days.

**Comment by aaaaalbert** [comment]
I chose to fix this problem by removing the check instead, 434ad0d9c8b8df2fe9102300ab4b03e1cfef97cd. Closing.
