### ISSUE TITLE
testportfiller.py does not replace <connport> properly

### ISSUE THREAD

**Issue by yyzhuang** [SeattleTestbed/nodemanager#104]
build.py calls buildcomponent https://github.com/SeattleTestbed/nodemanager/blob/master/scripts/build.py#L31 and this calls testportfiller.replace_ports: https://github.com/SeattleTestbed/common/blob/master/build_component.py#L339-L362

In testportfiller.py, it seems to replace ports in .py files, but not in .r2py files:

`for testfile in glob.glob("rs_*.py") + glob.glob("ut_*.py") + glob.glob("rn_*.py") + \
      glob.glob("rz_*.py") + glob.glob("rb_*.py") + glob.glob("ru_*.py") + \
      glob.glob("re_*.py") + glob.glob("rl_*.py") +glob.glob("s_*.py") + \
      glob.glob("n_*.py") + glob.glob("z_*.py") + glob.glob("b_*.py") + \
      glob.glob("u_*.py") + glob.glob("e_*.py") + glob.glob("l_*.py") + \
      glob.glob('restrictions.*') + glob.glob("ut_*.mix"):`

I suspect this is the reason when running ut_nm_validate_connection_limit.r2py and ut_nm_validate_connection_timeout.r2py, these errors occurred:

Exception (with type 'exceptions.Exception'): Failed to initialize the module (ut_nm_validate_connection_limit.r2py)! Got the following exception: 'CodeUnsafeError('Code failed safety check! Error: ("<type \'exceptions.SyntaxError\'> invalid syntax (line 45)",)',)'

Exception (with type 'exceptions.Exception'): Failed to initialize the module (ut_nm_validate_connection_timeout.r2py)! Got the following exception: 'CodeUnsafeError('Code failed safety check! Error: ("<type \'exceptions.SyntaxError\'> invalid syntax (line 41)",)',)'

**Comment by yyzhuang** [comment]
PR https://github.com/SeattleTestbed/common/pull/23

**Comment by choksi81** [comment]
PR: SeattleTestbed/common#23
