### ISSUE TITLE
Convert servicelogger.mix to servicelogger.py

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/nodemanager#24]
Can servicelogger.mix be changed to a python script by renaming it and making the following change?

```
29c29,30
< include servicelookup.repy
---
> import repyhelper
> repyhelper.translate_and_import('servicelookup.repy')
```

I'm not sure if it's that simple or if there's something else that needs to be done, but I would appreciate it as it would get a mix file out of my development process for seattlegeni (i don't use servicelogger in seattlegeni, but there's a chain of dependencies [believe from repyportability](I) that needs it).

**Comment by aaaaalbert** [comment]
Closing as WONTFIX. https://github.com/SeattleTestbed/nodemanager/blob/master/servicelogger.py is the relevant version for all future releases; I don't see us modifying the V1 nodemanager in this aspect before the switch to V2.
