### ISSUE TITLE
Nodemanager with shim has problem on testbed-xp2 due to firewall.

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/nodemanager#53]
When we run the nodemanager unit tests on testbed-xp2 using the nodemanager with shim implementation, then all the tests fail due to 'Connection refused' error. 

It seems that the firewall is blocking the connection and causing problems. When I turn off the firewall then all the tests pass. This is only for the new nodemanager with the shim implementation. 

The tests all pass with the production version of the nodemanager (without shim implementation), weather or not the firewall is turned on or not.

So it seems that there are some network calls with the new implementation thats not going through the windows firewall.

**Comment by aaaaalbert** [comment]
Closing this as shims have been superseded by Affix, and the current TCPRelayAffix works OK on a firewalled Windows machine.
