### ISSUE TITLE
repeated NMClient timeout exceptions from node 128.28.84.154.71

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/nodemanager#65]
Planet lab Node with IP 128.84.154.71 repeatably times out when attempted to be contacted including ssh. This has been occurring for weeks now.  Maybe we should have a check for this sort of behavior and mark the node inactive if it repeated causes errors over a period of time.

**Comment by aaaaalbert** [comment]
This specific node doesn't exist anymore. Nodemanager and clearinghouse are prepared for issues like these (auto-restart on boot; re-attempting to contact the NM when it is seen advertising).
