### ISSUE TITLE
Fix to #1231 needs to be ported over to branch

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/nodemanager#72]
A while back #1231 was addressed for the nodemanager on trunk. These changes need to be ported over to the RepyV2 nodemanager in branch. This will enable node tracking on the RepyV2 nodemanagers.

**Comment by aaaaalbert** [comment]
Fore reference, SeattleTestbed/attic#1231 was implemented to make node accounting easier from an interactive Python prompt with a simple call to the advertise functions. Unfortunately, the advertise rate that the nodes used to announce the accounting key was so high that they DDoSed the advertise servers.

IMHO tracking can be done just fine already using the service vessel pubkey so we shouldn't bother.

**Comment by aaaaalbert** [comment]
No further action required. Closing.
