### ISSUE TITLE
Node has duplicate state transition keys in vessels

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/nodemanager#79]
After running stat_lib.production_beta_key_split() on data that was polled on 2/8 18:10 (folder on blackbox: jeffra45/nodedata_2_8_1810) I found a node that had two vessels with the same [production key](https://seattle.cs.washington.edu/browser/seattle/trunk/seattlegeni/node_state_transitions/statekeys/movingtoonepercent_manyevents.publickey) in their corresponding userkey lists.

I have checked to see if this is still the case and ran experimentlib.browse_node() on the node in question and found it to still have the same duplicate keys in the userkey lists of vessel v3430 & v3429

Summary Info:

node ip: 137.226.138.154:1224
production key conflict: [movingtoonepercent_manyevents.publickey](https://seattle.cs.washington.edu/browser/seattle/trunk/seattlegeni/node_state_transitions/statekeys/movingtoonepercent_manyevents.publickey)
version: 0.1q
vessel names: v3430 & v3429

node id: '65537 97977742183520743665076736356425689510950675928689553187222188172360796340724194169529769501366697847098013514554685496950797288672367738074967064681321139875180612343607435275095362793760983867716343752472875326762784340263133766517655085833147445490933966737356868317433869313078953453980756197969793601089'

**Comment by aaaaalbert** [comment]
This was reported for a beta version long out of use since. Closing.
